config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :tickets
  resources :pizzas, except: [:index, :show]
  resources :ticket_pizzas, except: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
	has_one_attached :pic
	has_many :ticket_pizzas, dependent: :destroy
	has_many :tickets, through: :ticket_pizzas

	validates :name, presence: true, length: { minimum: 3, maximum: 35}
	validates :description, presence: true, length: { minimum: 25, maximum: 350}
	validates :price, presence: true, numericality: { only_integer: true }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	has_many :ticket_pizzas, dependent: :destroy
	has_many :ticket_user
	has_many :users, through: :ticket_user
	has_many :pizzas, through: :ticket_pizzas
end

app/models/ticket_pizza.rb
class TicketPizza < ApplicationRecord
	belongs_to :pizza
	belongs_to :ticket
end

app/models/ticket_user.rb
class TicketUser < ApplicationRecord
	belongs_to :user
	belongs_to :ticket
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ticket_users
  has_many :tickets, through: :ticket_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	skip_before_action :authenticate_user!, only: [:home]
	def home
		@ticket = Ticket.new
	end

end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController

	def new
		@pizza = Pizza.new
	end

	def create
		@pizza = Pizza.new(pizza_params)
		if @pizza.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@pizza = Pizza.find(params[:id])
	end

	def update
		@pizza = Pizza.find(params[:id])
		if @pizza.update(pizza_params)
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def destroy
		@pizza = Pizza.find(params[:id])
		@pizza.destroy
		redirect_to root_path
	end

	private

	def pizza_params
		params.require(:pizza).permit(:name, :description, :price, :pic)
	end
end

app/controllers/ticket_pizzas_controller.rb
class TicketPizzasController < ApplicationController
	respond_to :html, :js

	def new
		@ticket_pizza = TicketPizza.new
		@pizza = Pizza.all
		@ticket = Ticket.all
	end

	def create
		@pizza = Pizza.all
		@ticket_pizza = TicketPizza.new(ticket_pizza_params)
		if @ticket_pizza.save
			redirect_to ticket_path(id: @ticket_pizza.ticket.id)
		else
			redirect_to root_path
		end
	end

	def destroy
		@ticket_pizza = TicketPizza.find(params[:id])
		@ticket_pizza.destroy
		redirect_to ticket_path(id: @ticket_pizza.ticket.id)
	end

	private

	def ticket_pizza_params
		params.require(:ticket_pizza).permit(:ticket_id, :pizza_id)
	end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	respond_to :html, :js

	def index
		@tickets = Ticket.all
		@tp = TicketPizza.new
	end

	def show
		@ticket_pizzas = TicketPizza.all
		@ticket_pizza = TicketPizza.new
		@ticket = Ticket.find(params[:id])
		@pizzas = Pizza.all
	end

	def new
		@ticket = Ticket.new
	end

	def create
		@ticket = Ticket.new(ticket_params)
		if @ticket.save
			redirect_to @ticket
		else
			render 'new'
		end
	end

	def edit
		@ticket = Ticket.find(params[:id])
	end

	def update
		@ticket = Ticket.find(params[:id])
		if @ticket.update(ticket_params)
			redirect_to @ticket
		else
			render 'edit'
		end
	end

	def destroy
		@ticket = Ticket.find(params[:id])
		@ticket.destroy
		redirect_to root_path
	end

	private

	def ticket_params
		params.permit(:id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
	<%= link_to 'Pizz App', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      	<%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
    </ul>
    <ul class="navbar-nav dropleft">
    	<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle ml-auto" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
        	<% if !current_user.blank? %>
        		<%= link_to current_user.email, "#", class: "dropdown-item" %>
        	<% end %>
        	<% if !current_user.blank? %>
						<%= link_to "New Pizza", new_pizza_path, class: "dropdown-item" %>
        	<% end %>
        	<%= current_user.blank? ? (link_to 'Login', new_user_session_path, class: "dropdown-item") : 
						(link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item") %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PizzApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
  	<div class="container">
  		<%= yield %>
  	</div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row top-pad">
	<div class="col-md"></div>
	<div class="col-md align-self-center text-center">
		<div class="jumbotron">
		  <h1 class="display-4">Pizz-App!</h1>
		  <p class="lead">This is a simple pizza app, for testing purpose for RoR.</p>
		  <hr class="my-4">
		  <p>Create a Pizza order.</p>
		  <%= form_for @ticket do |f| %>
				<%= f.button 'New Order', class: "btn btn-primary btn-lg" %>
		  <% end %>
		</div>
	</div>
	<div class="col-md"></div>
</div>

app/views/pizzas/new.html.erb
<div class="row top-pad">
	<div class="col text-center">
		<h1>New Pizza</h1>
	</div>
</div>

<div class="row ">
	<div class="col-md">
		<%= form_for @pizza do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control", autofocus: true %>

			<%= f.label :description %>
			<%= f.text_area :description, class: "form-control" %>

			<%= f.label :price %>
			<%= f.text_field :price, class: "form-control" %>
			
			<%= f.label 'Picture' %>
			<%= f.file_field :pic, class: "form-control-file" %> <br>

			<%= f.button 'New Pizza', class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/ticket_pizzas/destroy.js.erb
$('#tick').html(" <% j (render 'tickets/ticket.html') %>")

app/views/ticket_pizzas/new.js.erb
$('#tick').html(" <% j (render 'tickets/ticket.html') %>")

app/views/ticket_pizzas/update.js.erb
$('#tick').html(" <% j (render 'tickets/ticket.html') %>")

app/views/tickets/_ticket.html.erb
<div class="row" >
	<div class="col-md" id="outprint">
		<table class="table table-dark" >
		  <thead>
		    <tr>
		      <th scope="col">Order</th>
		      <th scope="col">Price</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<% @ticket_pizzas.where(ticket_id: @ticket.id).each do |ticket_pizza| %>
			    <tr>
			      <td><%= ticket_pizza.pizza.name %></td>
						<td><%= number_to_currency(ticket_pizza.pizza.price, precision: 0) %></td>
						<td><%= link_to "<span class='close text-danger'>&times;</span>".html_safe, ticket_pizza_path(ticket_pizza), remote: true, method: :delete, data: {confirm: "Are you sure?"} %></td>
			    </tr>
		    <% end %>	
		  </tbody>
		    <tr>
		      <th scope="col">Total</th>
		      <th scope="col"><%= number_to_currency(@ticket.pizzas.sum(:price), precision: 0) %></th>
		    </tr>
		    <tr>
		    	<th scope="col">Staff:</th>
		      <th scope="col"><%= current_user.email %></th>
		    </tr>
		</table>
		<div class="row text-center">
			<div class="col-md">
				<%= image_tag("print.png", :width=>50, :height=>30, :onclick=>"PrintDiv();", :class=>'btn') %>

			</div>
		</div>
	</div>
</div>

<script type="text/javascript">     
  function PrintDiv() {    
     var divToPrint = document.getElementById('#outprint');
     var popupWin = window.open('', '_blank', 'width=300,height=300');
     popupWin.document.open();
     popupWin.document.write('<html><body onload="window.print()">' + divToPrint.innerHTML + '</html>');
      popupWin.document.close();
          }
</script>

app/views/tickets/_ticket.js.erb
$('#tick').html(" <% j (render 'ticket.html') %>")

app/views/tickets/edit.html.erb
edit.htl.erb

app/views/tickets/index.html.erb
index.html.erb

app/views/tickets/new.html.erb
new.html.erb

app/views/tickets/show.html.erb
<div class="row top-pad">
	<div class="col-md">
		<h1>New Order</h1>
	</div>
</div>

<div class="row align-items-start">
		<% @pizzas.each do |pizza| %>
			<div class="col-md">
				<div class="card" style="width: 12rem;">
				  <img src="<%= url_for(pizza.pic) %>" class="card-img-top" alt="...">
				  <div class="card-body">
				    <h5 class="card-title"><%= pizza.name %></h5>
				    <p class="card-text"><%= truncate(pizza.description, length: 25) %></p>
				    <p class="card-text">Price: <%= number_to_currency(pizza.price, precision: 0) %></p>
				    <div class="row">
				    	<div class="col-md text-center">
				    		<%= form_for @ticket_pizza, remote: true do |f| %>
				    			<%= f.hidden_field(:ticket_id, value: @ticket.id) %>
				    			<%= f.hidden_field(:pizza_id, value: pizza.id) %>
									<%= f.button 'Order', class: "btn btn-primary" %>
				    		<% end %>
				    	</div>
				    </div>
		  		</div>
				</div>
			</div>	
		<% end %>
	<div id="tick">
		<%= render 'ticket' %>
	</div>
</div>
